### ISSUE TITLE
Exhibit tags

### ISSUE THREAD

**Issue by jsimic** [uoregon-libraries/digital-exhibits-spotlight#104]
Working in the Doris Ulmann exhibit, display and entry of tags is problematic. This is a high priority for continued content ingest. 

1. Adding delimiter between tags, preferably a comma and space ", "

> [Current display](https://expo.uoregon.edu/spotlight/doris-ulmann/browse/group-portraits): PortraitsGroup portraitsRural lifeRural womenAppalachians (People)

> Preferred display: Portraits, Group portraits, Rural life, Rural women, Appalachians (People)

2. Change delimiter for entering tags from comma to pipe (“|”): It’s [currently a comma](https://expo.uoregon.edu/spotlight/doris-ulmann/catalog/df66x703p/edit) but this has created issues for tagging individuals in photos using the “last name, first name” format (the comma automatically designates the term following the comma as a new tag). Because of the current comma delimiter, all existing LCNAF/OPNS names are tagged as “First name Last Name.” Once the delimiter is changed, the names can be updated to reflect common standards (last name, first name)

**Comment by lsat12357** [comment]
change style selector to dd.blacklight-exhibit_tags a
