### ISSUE TITLE
pdf thumbnails

### ISSUE THREAD

**Issue by mfgaede** [uoregon-libraries/digital-exhibits-spotlight#18]
### Descriptive summary

Historical sheet music in Oregon Digital is in PDF form and is the majority of content for the "Music" section of the Public Domain exhibit. Would prefer not to reformat PDFs into images and upload separately if we don't have to. 

### Expected behavior

Content typically has a derivative thumbnail pulled, unsure how this is managed in OD, but it looks like the historical sheet music does have some sort of derivative image there. Can we snag that and bring it over to Spotlight? Right now it's showing a broken image thumb https://expo.uoregon.edu/spotlight/public-domain/catalog/admin, though it's brought over all the metadata cleanly. Would also be okay if I could just upload my own image as a placeholder and replace the broken thumb.

**Comment by lsat12357** [comment]
after upgrade to spotlight 3, document support unclear
