### ISSUE TITLE
Item Embed widget not pulling image

### ISSUE THREAD

**Issue by erastovich** [uoregon-libraries/digital-exhibits-spotlight#46]
When an item ingested from OregonDigital and a heading/text is added to the “Item Embed” widget, only the heading and text appear - no image appears.  The image should appear next to the heading and text. The widget works properly when it is a single item uploaded from a computer.

**Comment by lsat12357** [comment]
this particular widget displays images with OpenSeadragon Viewer; does not work with oembed assets (eg assets imported from OregonDigital). Will clarify in the widget labels/descriptions.

**Comment by lsat12357** [comment]
ok, code changes actually went in with PR #80
