### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by erastovich** [uoregon-libraries/digital-exhibits-spotlight#49]
### Descriptive summary 
When alternate languages are selected and translations are provided via an admin user, the navigation bar says, "Translation Missing”  

### Expected behavior 
When translations are provided under “Translations,” they should appear when the alternate language is selected by the user.

**Comment by lsat12357** [comment]
looks like this is configured in a file. If there is a language in particular that you want to add, we can collect the necessary translations and add the file.
