### ISSUE TITLE
Tags number inaccurate

### ISSUE THREAD

**Issue by erastovich** [uoregon-libraries/digital-exhibits-spotlight#53]
Under Curation --> Tags, it lists the tags within the exhibit and the number of items with that tag. However, the number reflects the number of items in all of UO's Spotlight with that tag, not the number of items just in that digital exhibit.

**Comment by lsat12357** [comment]
the tag count will still be slightly off in some exhibits until I remove ghost tags from the db (leftover from the oregondigital assets that were deleted)
