### ISSUE TITLE
IIIF error when adding thumbnails 

### ISSUE THREAD

**Issue by erastovich** [uoregon-libraries/digital-exhibits-spotlight#54]
An IIIF error message appears when a curator tries to add a thumbnail to a Page, Saved Search, or Browse Category. Admin users are able to add thumbnails without an error message.

**Comment by mfgaede** [comment]
Linked to #30

**Comment by lsat12357** [comment]
hm. this is not the role, but the type of asset. At the moment, images can only be used if they are uploaded, not imported using the OregonDigital importer.

**Comment by jsimic** [comment]
@lsat12357 This is still a problem and is blocking the Architecture of Oregon exhibit from being completed. FYI, admin user are also not able to us OD images.
<img width="980" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/6344086/183943632-ee3c64c6-1eac-4857-9d40-38edfc7b96bf.png">
