### ISSUE TITLE
Video widget usability

### ISSUE THREAD

**Issue by erastovich** [uoregon-libraries/digital-exhibits-spotlight#57]
In the Video widget, pasting the URL of a video works, but above that text box there is a box that says, “Drag video here.” That box does not work (I tried dragging an .mov and an .mp4). If we don't want drag & drop functionality, that box should be removed.

**Comment by lsat12357** [comment]
The widget currently works only with Youtube and Vimeo content; you can either paste the url in the field or drag the video from the Youtube/Vimeo page.  The Stanford folks have a ticket tagged 'icebox' for adding other sources.

**Comment by jsimic** [comment]
Can we add some verbage to the user interface that explains this?

**Comment by lsat12357** [comment]
already on it
